get http://localhost:3000/ads

###

post http://localhost:3000/ads
Content-Type: application/json

{
  "title": "Bike to sell",
  "description": "My bike is blue, working fine.",
  "owner": "bike.seller@gmail.com",
  "price": 100,
  "picture": "https://images.lecho.be/view?iid=dc:139656677&context=ONLINE&ratio=16/9&width=640&u=1562267496000",
  "location": "Paris",
	"categoryId": 2,
  "createdAt": "2023-09-05T10:13:14.755Z"
}

###

delete http://localhost:3000/ads/10
Content-Type: application/json

###

put http://localhost:3000/ads/2
Content-Type: application/json

{
	"id": 2,
	"title": "Car to sell",
	"description":
		"My car is blue, working fine. I'm selling it because I've got a new one",
	"owner": "car.seller@gmail.com",
	"price": 500,
	"picture":
		"https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
	"location": "Paris",
	"categoryId": 2,
	"createdAt": "2023-10-05T10:14:15.922Z"
}