post http://localhost:3000/categories
Content-Type: application/json

[
  {"title": "Ameublement"},
	{"title": "Electroménager"},
	{"title": "Informatique"},
	{"title": "Véhicules"},
	{"title": "Habillement"},
	{"title": "Outillage"},
	{"title": "Services"},
	{"title": "Other"}
]